version: "3.9"

services:
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_TCP_PORT: 3307
      MYSQL_DATABASE: "api_local"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - db_data:/var/lib/mysql
      - ./packages/prisma/prisma/seed.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "3307:3307"
volumes:
  db_data:
